### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by asr** [afl-eafit/2019-2-lab1#6]
@AlejandroMllo, the documentation for  `TransitionFunction` is incomplete. Please fix it.

**Comment by AlejandroMllo** [comment]
Done.

**Comment by asr** [comment]
Why did you erase my changes when fixing this issue?

**Comment by asr** [comment]
I'm waiting your answer.

**Comment by asr** [comment]
Never mind. I fixed the issue.
